  version: '3'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./homeassistant-entrypoint.sh:/docker-entrypoint.sh
        - ./homeassistant-entrypoint.py:/usr/src/app/homeassistant-entrypoint.py
      restart: always
      command: ["sh", "/docker-entrypoint.sh"]
      network_mode: host
