  version: '3'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - ~/.homeassistant/config:/config
        - /etc/localtime:/etc/localtime:ro
        - ./homeassistant-entrypoint.sh:/docker-entrypoint.sh
      restart: unless-stopped
      command: ["sh", "/docker-entrypoint.sh"]
      network_mode: host
